### PR TITLE
Add the option to provide ART and ERT keywords

### PR DESCRIPTION
**Pull request by gilbertmike**
@tanner-andrulis Is this the correct way to do to it? I.e., am I using the `add_attr` calls correctly and does the style match the project?

I also didn't put any tests.  If you think this is good, I'll think of some.

### CODE REVIEW

**Comment by tanner-andrulis** [comment]
It's an OK start, but there's no type checking inside the ERT/ART. We'd also need some objects to reflect their internal structures rather than just allowing an "anything" in that place

**Comment by gilbertmike** [comment]
I'm hitting a snag here.

The current version fails `test_eyeriss_like` in `test_compare`. This seems to be due to the ART and ERT keys not being removed even though they are not specified by the user, thus causing an error when ruamel attempts to stringify the `NotRequired` class.

This is not supposed to happen since the ART and ERT keys are supposed to be removed during parsing if the user does not provide them. The code that is supposed to remove them is in `_parse_elem`, which is called at the end of the ctors of `DictNode` and `ListNode`. This leads me to believe that somehow `_parse_elem` is either note being called or the ART and ERT keys are being added again after being removed.

**Comment by tanner-andrulis** [comment]
Try now. All tests are passing. Now the behavior is:
- ART & ERT are initialized with an empty tables list if not specified (so users may simply add to these tables if they desire, or they can overwrite).
- If ART and/or ERT tables are empty, they are not dumped

**Comment by gilbertmike** [comment]
@tanner-andrulis Thank you very much.

This last commit, [6218c46](https://github.com/Accelergy-Project/timeloopfe/pull/6/commits/6218c4669e4b67d5b084f280f75ed9a4b7e2b02d), cleans up the code I added to support my last commit, which is reverted to use your solution instead.

**Pull request merged**
